// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Api.Data;

#nullable disable

namespace Portfolio.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Api.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Portfolio.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 9, 4, 50, 13, 37, DateTimeKind.Utc).AddTicks(9515),
                            Description = "Dashboard วิเคราะห์ SMS: credit aggregation, sender-type charts, PHP dispatcher ที่สลับ query ตาม period",
                            Icon = "📊",
                            Name = "BlingSMS Analytics Dashboard",
                            SortOrder = 1,
                            Status = "Live",
                            TechStack = new[] { "PHP", "MySQL", "Chart.js" }
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 9, 4, 50, 13, 37, DateTimeKind.Utc).AddTicks(9523),
                            Description = "SQL pipeline สำหรับสรุปสถานะการส่งข้อความ (dn_status) แยกตาม gateway และช่วงเวลา",
                            Icon = "📁",
                            Name = "DN Analysis Report Engine",
                            SortOrder = 2,
                            Status = "Done",
                            TechStack = new[] { "SQL", "MySQL" }
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 9, 4, 50, 13, 37, DateTimeKind.Utc).AddTicks(9526),
                            Description = "สำรวจ API อ่านสลิปโอนเงินไทย เทียบ EasySlip กับ SlipOK",
                            Icon = "🔍",
                            Name = "Slip Verification Research",
                            SortOrder = 3,
                            Status = "R&D",
                            TechStack = new[] { "EasySlip", "SlipOK", "REST API" }
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 9, 4, 50, 13, 37, DateTimeKind.Utc).AddTicks(9528),
                            Description = "ซีรีส์วิดีโอตัวการ์ตูนผักในบริบทไทย ตัดต่อด้วย CapCut",
                            Icon = "🎬",
                            Name = "AI Character Video Series",
                            SortOrder = 4,
                            Status = "Creative",
                            TechStack = new[] { "CapCut", "AI Video" }
                        });
                });

            modelBuilder.Entity("Portfolio.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "PHP",
                            Proficiency = 80,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Database",
                            Name = "MySQL",
                            Proficiency = 75,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            Name = "Chart.js",
                            Proficiency = 95,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frontend",
                            Name = "Bootstrap",
                            Proficiency = 55,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Backend",
                            Name = "C# / .NET",
                            Proficiency = 40,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Backend",
                            Name = "Flask",
                            Proficiency = 50,
                            SortOrder = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
